apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}
  namespace: "{{.Values.app.namespace}}"
  labels:
    app: {{.Values.app.name}}
    team: {{.Values.app.namespace}}
    mail: "mephisto2120@gmail.com"
    owner: mephisto2120
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31100
      protocol: TCP
      name: http
    - name: metrics
      port: 8081
      targetPort: 8081
      nodePort: 31101
      protocol: TCP
  selector:
    app: {{.Values.app.name}}
