# Default values for dev environment
# TODO please set correct app name in docker-compose.yml - service name must be the same as image name.
app:
  name: service-template
  namespace: mephisto2120
  registry: registry-public.dev.sys
  replicas: 1
  profile: dev
  java:
    opts: >-
      -XX:+UseContainerSupport
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:HeapDumpPath=/dumps
      -Djava.security.egd=file:/dev/./urandom
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  probe:
    url: "/actuator/health"

image:
  version: -1
  buildTagVersion: auto

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80